name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-2019
    env:
      branch: Oct2020
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install choco packages
        run: choco install --no-progress -y winflexbison unzip curl
      
      - name: Get Golang
        run: choco install golang

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        # For some reason, the command is different than on linux/macos
        run: go test -short -v ./...

        