name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-2019
    env:
      branch: Oct2020
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install choco packages
        run: choco install --no-progress -y winflexbison unzip curl
      
      - name: Get Golang
        run: choco install golang

      - name: Build
        run: go build -v ./v2

      - name: Test
        run: go test -short -v ./v2

        